submitit WARNING (2025-05-26 19:06:00,559) - Bypassing signal SIGCONT
submitit WARNING (2025-05-26 19:06:00,559) - Caught signal SIGUSR2 on ad12a3ca-02.cloud.together.ai: this job is timed-out.
--- Logging error ---
Traceback (most recent call last):
  File "/home/c-cye/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/logging/__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/submitit/core/job_environment.py", line 226, in checkpoint_and_try_requeue
    raise utils.UncompletedJobError(message)
submitit.core.utils.UncompletedJobError: Job not requeued because: timed-out and not checkpointable.
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/submitit/core/submission.py", line 76, in submitit_main
    process_job(args.folder)
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/submitit/core/submission.py", line 55, in process_job
    result = delayed.result()
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/submitit/core/utils.py", line 137, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "/home/c-cye/assignment4-data/cs336_data/first_filter.py", line 160, in process_batch_of_wet_files
    for wet_filepath in wet_filepaths_batch:
  File "/home/c-cye/assignment4-data/cs336_data/first_filter.py", line 85, in process_single_wet_file
    # filter with gopher
  File "/home/c-cye/assignment4-data/cs336_data/gopher.py", line 34, in filter
    tokenized = self.tokenize(text)
  File "/home/c-cye/assignment4-data/cs336_data/gopher.py", line 81, in tokenize
    return nltk.tokenize.word_tokenize(text)
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/nltk/tokenize/__init__.py", line 142, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/nltk/tokenize/__init__.py", line 120, in sent_tokenize
    return tokenizer.tokenize(text)
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/nltk/tokenize/punkt.py", line 1280, in tokenize
    return list(self.sentences_from_text(text, realign_boundaries))
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/nltk/tokenize/punkt.py", line 1340, in sentences_from_text
    return [text[s:e] for s, e in self.span_tokenize(text, realign_boundaries)]
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/nltk/tokenize/punkt.py", line 1328, in span_tokenize
    for sentence in slices:
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/nltk/tokenize/punkt.py", line 1457, in _realign_boundaries
    for sentence1, sentence2 in _pair_iter(slices):
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/nltk/tokenize/punkt.py", line 324, in _pair_iter
    for el in iterator:
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/nltk/tokenize/punkt.py", line 1434, in _slices_from_text
    last_break = match.start("next_tok")
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/submitit/core/job_environment.py", line 196, in bypass
    self._logger.warning(f"Bypassing signal {signal.Signals(signum).name}")
Message: 'Bypassing signal SIGCONT'
Arguments: ()
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
