submitit WARNING (2025-05-27 00:22:01,018) - Bypassing signal SIGCONT
submitit WARNING (2025-05-27 00:22:01,022) - Caught signal SIGUSR2 on ad12a3ca-01.cloud.together.ai: this job is timed-out.
--- Logging error ---
Traceback (most recent call last):
  File "/home/c-cye/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/logging/__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/submitit/core/job_environment.py", line 226, in checkpoint_and_try_requeue
    raise utils.UncompletedJobError(message)
submitit.core.utils.UncompletedJobError: Job not requeued because: timed-out and not checkpointable.
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/submitit/core/submission.py", line 76, in submitit_main
    process_job(args.folder)
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/submitit/core/submission.py", line 55, in process_job
    result = delayed.result()
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/submitit/core/utils.py", line 137, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "/home/c-cye/assignment4-data/cs336_data/first_filter.py", line 174, in process_batch_of_wet_files
    result = process_single_wet_file(wet_filepath, output_path, work_dir)
  File "/home/c-cye/assignment4-data/cs336_data/first_filter.py", line 81, in process_single_wet_file
    language, langconf = language_detector.detect_language(text)
  File "/home/c-cye/assignment4-data/cs336_data/utils.py", line 108, in detect_language
    return filter_fasttext(text, self.classifier)
  File "/home/c-cye/assignment4-data/cs336_data/utils.py", line 90, in filter_fasttext
    prediction = classifier.predict(text)
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/fasttext/FastText.py", line 233, in predict
    predictions = self.f.predict(text, k, threshold, on_unicode_error)
  File "/home/c-cye/assignment4-data/.venv/lib/python3.13/site-packages/submitit/core/job_environment.py", line 196, in bypass
    self._logger.warning(f"Bypassing signal {signal.Signals(signum).name}")
Message: 'Bypassing signal SIGCONT'
Arguments: ()
